# Site settings
title: Joe Marshall - Human Computer Interaction Research
email: joe.marshall@nottingham.ac.uk
description: Slick Material Design theme for Jekyll powered by Material Design Lite.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
copyright: 

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: blue-deep_orange

# Google Analytics account ID (UA-XXXXXXXX-X)

google-analytics-ua: UA-84475574-1
keep_files: ["uploads"]

permalink: /:year/:month/:day/:title.html

collections:
    pubs:
        output: true
        path: ../_posts
        permalink: /awesome/:path/:title.:output_ext